### ISSUE TITLE
Delete mistaken / inaccurate presses

### ISSUE THREAD

**Issue by malangela** [myclasp/Barnacle#2]
hello,
I have been using SnAPP and definetly I would need a simple way of (at least) deleting unwanted , inaccurate or irrelevant presses. for example:
- I press the button twice too slowly and Snapp records it as an 'UP': i would like to delete that log.
- I start the GPS, I wait for a while, i press the button, the reponse is stilll delayed -  looking for the GPS signal, i guess. My instinct makes me press it several times again. These presses are then queued and then log: I'd like to delete redundant logs.

this is very much in line to our the summer project participants feedback:

_"knowing what that should be discounted"..."Like any spreadsheet that would be useful ‘cos then if you’ve got it from week-to-week you might not remember in a month’s time what happened so if you go at the end of the day and have a look and go, oh at two o’clock I used it 25 times, I was just fiddling with it, that doctor is going to think I had an anxiety attack so let me just change it, and then put a note in that says I was just fiddling with it, and then it changes everything doesn’t it, so yeah probably need to do that"_

**Comment by adriangradinar** [comment]
Based on internal team discussions, we're implementing a 'swipe to mark' algorithm.
