### ISSUE TITLE
Color coding swap??

### ISSUE THREAD

**Issue by malangela** [myclasp/Barnacle#3]
Adrian, could you check what colour you have assigned to what in the 'Last 7 days view'?
Example: 07 April on my phone
- 4 interaction in total of which: 3 UP; 1 DOWN
- 'Last 7 Days' view:  the DOWN blue chart is highlighted with a score of 3; the orange bar is faded and records 1 score. - an accidental swap of colours in the code?
- 'Current Month' view gives me an orange blob, which is correct.

m

**Comment by adriangradinar** [comment]
Should be fixed in v0.3.5 now but please check again!
